#!/usr/bin/env bash

if [[ "$1" =~ ^[0-9]+$ ]]; then
  num="$1"
  shift
  samtools view -h "$@" | flags-to-bits | column -t -s$'\t' | head -n "$num"
else
  samtools view -h "$@" | flags-to-bits | column -t -s$'\t' | head
fi
